# Generated by Django 4.0.2 on 2022-03-01 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('phone', models.CharField(max_length=11, verbose_name='telefone')),
                ('address', models.CharField(default='', max_length=100, verbose_name='endereço')),
                ('cargo', models.CharField(choices=[('1', 'Designer'), ('2', 'Redator'), ('3', 'Analista de Dados'), ('3', 'Gerente de Comunidade'), ('4', 'Planner'), ('5', 'Arte Finalista'), ('6', 'Designer 3D'), ('7', 'Atendimento')], default='1', max_length=30, verbose_name='cargo')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('+', 'LGBTQIA+'), ('N', 'Nenhuma das opções')], default='N', max_length=1, verbose_name='sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dado Complementar',
                'verbose_name_plural': 'Dados Complementares',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
