# Generated by Django 4.0.2 on 2022-03-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplete',
            name='dob',
            field=models.DateTimeField(null=True, verbose_name='data de nascimento'),
        ),
    ]
