# Generated by Django 4.0.2 on 2022-03-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='com',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='comprometimento'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='cpi',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='cumprimento dos processos internos'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='cup',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='cumprir prazos'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='err',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='erros'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='fle',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='flexibilidade'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='ini',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='iniciativa'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='lid',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='liderança'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='org',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='p_neg',
            field=models.TextField(blank=True, max_length=200, verbose_name='percepções negativas'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='p_pos',
            field=models.TextField(blank=True, max_length=200, verbose_name='percepções positivas'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='pon',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='pontualidade'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='pro',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='proatividade'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='pst',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='proficiência em softwares e técnicas'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='tee',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='0', verbose_name='trabalho em equipe'),
        ),
    ]
