# Generated by Django 4.0.2 on 2022-03-16 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aval', '0002_alter_avaliation_com_alter_avaliation_cpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
